### ISSUE TITLE
Button causes error

### ISSUE THREAD

**Issue by pmichaelis** [juergenweb/FrontendForms#1]
Hey,

the form button produces an error:

Call to undefined function _(), did you mean d()?
File: [.../FrontendForms/Formelements/Miscellaneous/Button.php:27]

27:            $this->setAttribute('value', _('Send')); // default is "Send"

I think it must be __('Send)

**Comment by juergenweb** [comment]
Hello pmichaelis

Thanks for reporting this issue. I have added the missing $this in front of the translatable string (of course you can also write it with 2 underscores as you suggested).

Have a nice day
