### ISSUE TITLE
Error when installning module

### ISSUE THREAD

**Issue by flashmaster82** [juergenweb/FrontendForms#1]
Parse Error: syntax error, unexpected 'Validator' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) (line 20 of E:\Wamp\www\Website\site\modules\FrontendForms\FrontendForms.module)

**Comment by juergenweb** [comment]
As written in the PW forum - this will be caused by using a PHP version, which does not support type hinting. Upgrading to a higher PHP version (at least 7.4) will solve the problem.

**Comment by flydev-fr** [comment]
https://github.com/juergenweb/FrontendForms/blob/6aa816f0abe691ca74a4f4b9d850fb41198f283d/FrontendForms.module#L29

@juergenweb if you look at the props declaration, you used **Union Type** (`protected string|int`) then PHP-8 is required to interpret that.
