### ISSUE TITLE
Using `Markup` input class causes error

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#16]
Hi @juergenweb, here I am again with a bug report :)
I believe in one of newer than 2.2.3 versions `Markup` element stopped working:
![SCR-20240829-rzkb](https://github.com/user-attachments/assets/d11aecee-d852-46f7-8490-1cc0f08152b4)

As I understand it get's called a method as any other input, but it doesn't have that method implemented, so it errors out.
My quick and dirty fix was to make `Markup` class extend `TextElements` or `Element` class and that makes the error go away, as it gets recognised as not an input then.

```php
class Markup extends Element {...
// or
class Markup extends TextElements {...
```

But an official bugfix would make sure it's properly done.
Have a great day!

**Comment by juergenweb** [comment]
Hello @donatasben 

Thanks for reporting another issue. I have fixed it now and it will be included in the next update ([changelog.md](https://github.com/juergenweb/FrontendForms/blob/main/CHANGELOG.md#2024-08-30)), so I close this issue now.
