### ISSUE TITLE
FF tries to call a function with the name of page title

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#18]
HI @juergenweb,
I see I am receiving quite a lot of such notices in my TracyAdmin logs:
![SCR-20241005-cedr](https://github.com/user-attachments/assets/deab1769-3411-44bd-b739-cccb3a3cf6e0)

It seems that FrontendForms is trying to use a PHP file that is in the name of current page. Maybe it's looking to load a form?
Is it possible to disable this?

Thanks!

**Comment by juergenweb** [comment]
Hello @donatasben 

I do not know this warning message before and I cannot reproduce it on my local server, but after asking google it seems that it has something to do with your server settings:

"
To resolve this error, you must edit the file httpd.conf. Way before it can be seen in phpinfo in apache2handler section directive Server Root. For example, in my case this way - / etc / httpd / httpd.conf. Open the file httpd.conf, find the mention of the parameter open_basedir. And set it to none. (php_admin_value open_basedir none)
"
Source: https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

Not sure, but it seems that it has something to do with your server setup. I am afraid, but I think I cannot change something in the code to prevent this behavior.

Best regards Jürgen
