### ISSUE TITLE
Time-trap Spam protection setting not persisting

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#2]
When changing setting for amount of seconds on "Measure 2: Time-trap" in module settings on admin - it doesn't save it, reverts back to initial setting of "5".
I can manually change on database level and the setting works as it should, but not when changing on admin.
<img width="710" alt="SCR-20231227-mlrt" src="https://github.com/juergenweb/FrontendForms/assets/4421344/6d0b79c2-e32f-47a3-951e-b117b01395e2">

**Comment by juergenweb** [comment]
You are right. There was the name attribute on the inputfield missing. Maybe it was a copy/paste issue. Now it has been added again on line 1746 and changes will be taken into account. 
I bump up the version later. For now you can replace the old file with the new one to solve this issue.

Thank you for reporting this!
