### ISSUE TITLE
Inputfieldcheckox 

### ISSUE THREAD

**Issue by pmichaelis** [juergenweb/FrontendForms#2]
Hey,

the checkbox example code:

$privacy = new InputCheckbox('privacy');
$privacy->setLabel('I accept the privacy policy');
$privacy->setRule('required')->setCustomMessage('You have to accept our privacy policy');
$form->add($privacy);

produces the following error, when the checkbox is added to the form:

[/FrontendForms/Formelements/Inputelements/Inputfields.php:465]

TypeError
Return value of [FrontendForms\Inputfields::getPostValue]
() must be an instance of FrontendForms\mixed, array returned

**Comment by juergenweb** [comment]
Hello Phillip

PHP storm has added a PHP 8 return type declaration. I have removed it. Please try it again and let me know if the problem still persists.

Best regards

**Comment by juergenweb** [comment]
Thanks for your feedback.
