### ISSUE TITLE
Reference Error: mfConditionalFields is not defined

### ISSUE THREAD

**Issue by sdenec** [juergenweb/FrontendForms#22]
There seems to be an error regarding mfConditional fields. 
I get the following error message using firefox:

Uncaught ReferenceError: mfConditionalFields is not defined
    <anonymous> https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1
    frontendformsmain https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1
    <anonymous> https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1
[frontendforms.min.js:1:1307](https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24)
    <anonym> https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1
    (Async: EventListener.handleEvent)
    frontendformsmain https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1
    <anonym> https://[...]/site/modules/FrontendForms/frontendforms.min.js?v=2.2.24:1

**Comment by juergenweb** [comment]
Hello @sdenec 

Thank you for reporting this issue. Unfortunately, I can't reproduce this error message on my part. I suspect there was a problem with minifying the JS file.
I've now minimized it with another minifier program. Would you be so kind to replace your version of the frontendforms.min.js with the one I have uploaded now on [Github](https://github.com/juergenweb/FrontendForms/blob/main/frontendforms.min.js) and give me a feedback if it works now. 

If not, could you make a screenshot of the errormessage in firefox?

Best regards Jürgen

**Comment by juergenweb** [comment]
I've added a check to see if *mfConditionalFields* isn't defined. This is the case when there are no conditional fields within a form and therefore the mf-conditional-fields.min.js. is not inserted into the HTML code of the page. This should be responsible for the error message.

Replace the *frontendforms.min.js* from GitHub with yours  and let me know if it works now.

**Comment by juergenweb** [comment]
I have checked it on my local installation with or without the if-condition in the frontendforms.min.js and it the error is gone. So I have updated the module to version to 2.2.25.

Please update the module now and let me know if it works on your site to (You do not need to replace the file as written above).

**Comment by sdenec** [comment]
I can confirm with the new update the error is gone! Thank you :)
