### ISSUE TITLE
Warning in module foreach loop getting requirementsLabels setting for passwords

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#3]
TracyDebugger reports a warning when opening module configuration admin page:
```
PHP Warning: foreach() argument must be of type array|object, null given in .../site/modules/FrontendForms/FrontendForms.module:2017
```

**Comment by juergenweb** [comment]
Line 2017 in the FrontendForms.module file of the current version is a comment and not a foreach loop ?!?

` // DISTORTION LINES`

Please press the "Refresh" button for the modules to clear the modules cache and check if the warning is gone.

**Comment by donatasben** [comment]
Sorry, it was for the older module version. There's no error in the newest version. My bad ☺️
