### ISSUE TITLE
Deprecation warning for setOption() on InputCheckboxMultiple::$topLabel

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#4]
TracyDebugger reports a deprecation error when setting `InputCheckboxMultiple` options with `setOption('Label', 'value')` on PHP 8.2:

`PHP Deprecated: Creation of dynamic property FrontendForms\InputCheckboxMultiple::$topLabel is deprecated in .../Formelements/Inputelements/Inputs/InputCheckboxMultiple.php:40`

**Comment by juergenweb** [comment]
Missing declaration for property $topLabel added.
Thank you for reporting this issue!!
