### ISSUE TITLE
Feature request: allow custom paths in mailTemplate()

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#6]
Hi,
I was wondering if it would be possible for you to make the setting `mailTemplate()` to accept custom file paths, not only template file name - so that the desired email template could be stored wherever is convenient? Not only in the defined specific `/site/frontendforms-custom-templates`.

If it is just a file name - then it could search within known location, like "/site/frontendforms-custom-templates".

That would be very helpful! :)

**Comment by juergenweb** [comment]
Hello

Could you please describe, what is the sense of such an addition. Why do you want to store template files outside of the given folder.
To implement such a new feature I need to know what could be the benefit of it.


Best regards

**Comment by juergenweb** [comment]
Hello Donatas

I have added your request to the latest version 2.1.61, because it was not a big deal to implement it.

Please read the full instructions inside the [changelog.md](https://github.com/juergenweb/FrontendForms/blob/main/CHANGELOG.md#2161-2024-02-03).

If this works for you please close this thread after successful testing.

Best regards Jürgen

**Comment by donatasben** [comment]
Thank you Jürgen! That was fast 😄 

My need is that I use separate modules to implement FrontendForms forms on my several projects. One form is sending mail to admins, others back to the users, etc. - I want them to have different template files. And to easier distribute and push to Git I want to bundle everything for each form to its own module folder - including email template files.

And thanks to you now I can! 🥳

**Comment by juergenweb** [comment]
OK, this makes sense to me!

I will close this request now, because the addition has been added. If you discover some problems, please open a new issue report.
